### ISSUE TITLE
Tip: You Can Download All Punks in One Image (punks.png)

### ISSUE THREAD

**Issue by geraldb** [Rphad/Cryptopunk-Colors#1]
Hello,

  First - looking forward to learning more about the colors of cryptopunks. 

> First, I downloaded all 10k images from the Larvalabs website using a Shell script. 

 Just a little tip you can download all punks in a single official ~800k image (with the certified hash on the blockchain), see <https://github.com/larvalabs/cryptopunks/blob/master/punks.png>. That might make it easier to analyse all punks / colors (in the original 24x24 px format). 

 Anyways, keep up your great work and thanks for sharing.

PS:  I  published a post about your scripts to the [**r/CryptoPunksDev**](https://old.reddit.com/r/CryptoPunksDev/) channel titled [**Inside the 8-Bit CryptoPunks Pixel Art - All 228 Colors - Using R Script to Gather Color Statistics**](https://old.reddit.com/r/CryptoPunksDev/comments/p4b5pp/inside_the_8bit_cryptopunks_pixel_art_all_228/).

**Comment by raphdeknop** [comment]
That's of course better thanks. The thing is that I wrote a script to get the skin color of each punk first (didn't find any csv which contained it online), which I achieved by looking at the last row only ([,336,]). Then, I just added a loop to look at *all* the colors.

**Comment by geraldb** [comment]
Again thanks for sharing. Keep it up. Cheers. Prost.  PS: Might be a great addition to publish your skin color script. For refeference and an alternate way (using ruby) see my little [skintone script](https://github.com/cryptopunksnotdead/cryptopunks/blob/master/colors/skintone.rb).

**Comment by raphdeknop** [comment]
Made some changes. I used the big image & imagemagick to do it. It's wayy faster haha ! I even used imagemagick for plotting. I might add more explanations in the readme (and maybe delete the R files ?) but I already added details !
